import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Sidebar from "./_components/Sidebar";
import Navbar from "./_components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const font = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.variable
        )}>
        <main className="w-full h-full flex">
          <section className="basis-2/12 h-screen border-r px-4">
            <Sidebar />
          </section>
          <section className="basis-10/12 h-full">
            <Navbar />
            <div className="p-5"> {children}</div>
            <Toaster />
          </section>
        </main>
      </body>
    </html>
  );
}
