import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Topbar from "./_components/Topbar";
import ClientLayout from "./_components/ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("dark", GeistSans.className)}>
      <body
        className={cn("bg-background font-sans antialiased overflow-hidden")}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <div className="hidden border-r bg-muted/40 md:block">
            <Sidebar />
          </div>
          <div className="flex flex-col">
            <Topbar />
            <main className="flex flex-1 flex-col">
              <div className="h-[90vh] overflow-y-auto p-4 lg:p-6">
                <ClientLayout>{children}</ClientLayout>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
