import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import RightSideMenuDropdown from "./_components/RightSideMenuDropdown";
import LeftSideSearchInput from "./_components/LeftSideSearchInput";
import SmallScreenSidebar from "./_components/SmallScreenSidebar";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Topbar from "./_components/Topbar";

// const font = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("dark", GeistSans.className)}>
      <body
        className={cn("bg-background font-sans antialiased overflow-hidden")}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <div className="hidden border-r bg-muted/40 md:block">
            <Sidebar />
          </div>
          <div className="flex flex-col">
            <Topbar />
            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
              <div>
                {children}
                <Toaster />
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
